version: '3'

services:
  db:
    image: postgres:12.4-alpine
    restart: always
    volumes:
      - /srv/nextcloud/db:/var/lib/postgresql/data
    env_file:
      - db.env

  redis:
    image: redis:alpine
    restart: always

  app:
    user: "1000:1000"
    image: nextcloud:23.0.11-fpm-alpine
    restart: always
    volumes:
      - /home/admin/ossfs/nextcloud:/var/www/html
    environment:
      - POSTGRES_HOST=db
      - REDIS_HOST=redis
    env_file:
      - db.env
    depends_on:
      - db
      - redis

  web:
    user: "1000:1000"
    build: ./web
    restart: always
    volumes:
      - /home/admin/ossfs/nextcloud:/var/www/html:ro
    environment:
      - VIRTUAL_HOST=pan.kws.knd.com.cn
      - LETSENCRYPT_HOST=pan.kws.knd.com.cn
      - LETSENCRYPT_EMAIL=zhangxu@knd.com.cn
    depends_on:
      - app
    networks:
      - proxy-tier
      - default

  cron:
    user: "1000:1000"
    image: nextcloud:23.0.11-fpm-alpine
    restart: always
    volumes:
      - /home/admin/ossfs/nextcloud:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis

  proxy:
    build: ./proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    volumes:
      - /srv/nextcloud/certs:/etc/nginx/certs:ro
      - /srv/nextcloud/vhost.d:/etc/nginx/vhost.d
      - /srv/nextcloud/html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy-tier

  letsencrypt-companion:
    image: nginxproxy/acme-companion:2.2
    restart: always
    volumes:
      - /srv/nextcloud/certs:/etc/nginx/certs
      - /srv/nextcloud/acme:/etc/acme.sh
      - /srv/nextcloud/vhost.d:/etc/nginx/vhost.d
      - /srv/nextcloud/html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy-tier
    depends_on:
      - proxy

# omgwtfssl:
#    image: paulczar/omgwtfssl
#    restart: "no"
#    volumes:
#      - certs:/certs
#    environment:
#      - SSL_SUBJECT=servhostname.local
#      - CA_SUBJECT=my@example.com
#      - SSL_KEY=/certs/servhostname.local.key
#      - SSL_CSR=/certs/servhostname.local.csr
#      - SSL_CERT=/certs/servhostname.local.crt
#    networks:
#      - proxy-tier

networks:
  proxy-tier: